#include "main.cpp"
#include "texture.cpp"
#include "renderer.cpp"
#include "system.cpp"
#include "common.cpp"
#include "win_hotload.cpp"
#include "entity.cpp"
#include "editor.cpp"
#include "input.cpp"

#include "imgui/imgui.cpp"
#include "imgui/imgui_widgets.cpp"
#include "imgui/imgui_draw.cpp"
#include "imgui/imgui_demo.cpp"
#include "imgui/imgui_impl_sdl.cpp"
#include "imgui/imgui_impl_opengl3.cpp"